//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoEcole
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class autoEcoleDBEntities : DbContext
    {
        public autoEcoleDBEntities()
            : base("name=autoEcoleDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Paiement> Paiements { get; set; }
        public virtual DbSet<Participan_typePermi> Participan_typePermi { get; set; }
        public virtual DbSet<TParticipant> TParticipants { get; set; }
        public virtual DbSet<typePermi> typePermis { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
